Geometry DEFINITIONS ::= BEGIN

Point ::= SEQUENCE {
	x	INTEGER,
	y	INTEGER
}

Line ::= SEQUENCE {
	p1	Point,
	p2	Point
}

Rectangle ::= SEQUENCE {
	width	INTEGER (0..18446744073709551616),
	height	INTEGER (0..18446744073709551616)
}

END
