[package]
name = "serde_asn1"
version = "0.1.0"
authors = ["Josh Mcguigan"]
edition = "2018"

[workspace]
members = ["serde_asn1_codegen"]

[dependencies]
serde = "1.0"
serde_asn1_codegen = { path = "serde_asn1_codegen" }

[dev-dependencies]
serde_derive = "1.0"
serde_json = "1.0"
hex = "0.4"
